### ISSUE TITLE
Add support for AW RP150

### ISSUE THREAD

**Issue by Dev1an** [Dev1an/Awrp50#1]
https://github.com/Dev1an/Awrp50/blob/b7848884ab5168bb5c5cd4e7064619a49086a7b3/index.js#L16

RP150 uses
`SBUS:[0-9]{2,3}:[0-9]{2}` new regular expression
`SBUS:<Channel>:<Cam>` description
 - Channel:
   - Aux: `"113"` -> `"115"`
   - ME1PVW: `"02"`
 - Cam: `"01"` -> `"05"`

Raw messages:
 - Aux 1: `SBUS:113:01SBUS:113:02SBUS:113:03SBUS:113:04`
 - Aux 2: `SBUS:114:01SBUS:114:02SBUS:114:03SBUS:114:04`
 - Aux 3: `SBUS:115:01SBUS:115:02SBUS:115:03SBUS:115:04`
 - ME1PVW: `SBUS:02:01SBUS:02:02SBUS:02:03SBUS:02:04`

**Comment by MichelDufaux** [comment]
Here's the full list of busses:
- ME1PVW 	= `SBUS:02`
- ME1KEY1-F 	= `SBUS:03`
- ME1KEY1-S	= `SBUS:04`
- ME1KEY2-F 	= `SBUS:05`
- ME1KEY2-S	= `SBUS:06`
- ME1KEY3-F 	= `SBUS:07`
- ME1KEY3-S	= `SBUS:08`
- ME1KEY4-F 	= `SBUS:09`
- ME1KEY4-S	= `SBUS:10`
- ME2PVW		= `SBUS:14`
- …
- ME2KEY4-S	= `SBUS:22`
- DSK1-F		= `SBUS:97`
- DSK1-S		= `SBUS:98`
- …
- DSK4-S		= `SBUS:104`
- AUX1 		= `SBUS:113`
- …
- AUX16 		= `SBUS:128`

**Comment by Dev1an** [comment]
support for RP150 is added in version 1.0.0
